FROM python:3.8.9

# Set the WORKDIR to /app so all following commands run in /app
WORKDIR /app

# Adding (dev-)requirements files before installing requirements
COPY requirements.txt dev-requirements.txt ./

# Install requirements and dev requirements through pip. Those should include
# nostest, pytest or any other test framework you use
RUN pip install -r requirements.txt -r dev-requirements.txt

# Adding the rest of your project code to the image
COPY . ./
